remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: Leonardo Emili
description: Machine Translation <a href="https://www.linkedin.com/company/apple/" target=”_blank”>@Apple</a><br>CS <a href="https://www.linkedin.com/school/sapienzauniversitadiroma" target=”_blank”>@Sapienza</a>/<a href="https://www.linkedin.com/school/tuwien" target=”_blank”>@TUWien</a><br>Prev <a href="https://www.linkedin.com/company/translated" target=”_blank”>@Translated</a>/<a href="https://www.linkedin.com/company/apple" target=”_blank”>@Siri</a><br>Natural Language Processing and Deep Learning enthusiast.
show_downloads: false
logo: https://github.com/LeonardoEmili.png?size=256
github: [metadata]
color-scheme: auto
